### ISSUE TITLE
smarcheet

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-gestion-de-proyectos#1]
[Smart Sheet.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-gestion-de-proyectos/files/9931816/Smart.Sheet.pdf)

**Comment by IsraelNicolas61** [comment]
20/20
¡Buen trabajo!

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
